default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: rails_4_2_and_rspec_development

test:
  <<: *default
  database: rails_4_2_and_rspec_test

production:
  <<: *default
  database: rails_4_2_and_rspec_production
